### PR TITLE
Furkan/frontend/add application page

### PR DESCRIPTION
**Pull request by FurkannOzbek**
#   Move Add Application Component to Separate Page 

---

## Description

This PR refactors the Add Application feature by moving it to a dedicated page, improving navigation and UI clarity. The Add Application button on the Dashboard has been updated to redirect to the new page, and minor CSS changes were made for enhanced styling and consistency.

---

## Changes Made

List the main changes in this pull request. Describe what was added, modified, or removed.

 **Frontend:**  
-  Moved the Add Application component to its own standalone page.
- Updated the Dashboard Add Application button to redirect to the new page.
- Made minor CSS adjustments to improve UI consistency.

---

## Screenshots (if applicable)

add app 3

---

## Testing Steps

1. **Frontend:** New page can be tested on root/applications/add  after user login

---

### CODE REVIEW

**Comment by pankaj28843** [comment]
How does it look in mobile phones?

**Comment by Natata08** [comment]
image

**Comment by FurkannOzbek** [comment]
New error check

If an application already exists with the same company name, job title, and user, an error will be displayed to prevent duplicate submissions

**Review by magdazelena — APPROVED** [review]
looking good! nice work :)

**Pull request merged**
